# Generated by Django 2.0.1 on 2018-01-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorty', '0004_auto_20180114_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('skrc_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shorty.SkrcUrl')),
            ],
        ),
    ]
