# Generated by Django 2.0.1 on 2018-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180114_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
