# Generated by Django 2.0.1 on 2018-01-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skrcurl',
            old_name='shorturl',
            new_name='shortcode',
        ),
    ]
