# Generated by Django 2.0.1 on 2018-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_auto_20180113_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skrcurl',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
